# Generated by Django 5.2.14 on 2026-05-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLQueryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('execution_time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_queries', to='metrics.apimetric')),
            ],
        ),
    ]
