# Generated by Django 5.2.14 on 2026-05-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_dummydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('slow_api', 'Slow API'), ('slow_query', 'Slow Query'), ('high_query_count', 'High Query Count')], max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='metrics.apimetric')),
            ],
        ),
    ]
