# Generated by Django 5.2.14 on 2026-06-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_performanceissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceissue',
            name='issue_type',
            field=models.CharField(choices=[('slow_api', 'Slow API'), ('slow_query', 'Slow Query'), ('high_query_count', 'High Query Count'), ('n_plus_one', 'N+1 Query'), ('regression', 'Performance Regression')], max_length=50),
        ),
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(max_length=100)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='metrics.apimetric')),
            ],
        ),
    ]
