server {
    listen 80;

    location / {
        proxy_pass http://backend:8000;

        proxy_set_header Host $host; # stored in host variable, passed to backend
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

"""
These lines in NGINX pass original client request information from Nginx to your Django backend.

Without them, backend may only see:

request coming from Nginx container
not actual user/client details

Your config:

proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
1. Host Header
proxy_set_header Host $host;

Passes original hostname.

Example request:

http://myapi.com/api/health/

Then:

Host = myapi.com

gets forwarded to Django.

Why important?

Django uses Host header for:

ALLOWED_HOSTS
domain logic
URL generation
security

Without this line backend may see:

Host: backend

instead of actual domain/IP.

2. Real Client IP
proxy_set_header X-Real-IP $remote_addr;

Passes actual user IP.

Example:

User IP = 192.168.1.10

Nginx forwards:

X-Real-IP: 192.168.1.10

to Django.

Without this:

Backend may think every request comes from:

nginx container IP

which is wrong.

Useful for:

logging
rate limiting
audit trails
analytics
security monitoring
3. Forwarded Chain
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

Tracks FULL proxy chain.

Example:

Client → Load Balancer → Nginx → Django

Header becomes:

X-Forwarded-For:
192.168.1.10, 10.0.0.5

So backend knows complete path.

Difference between:

Header	Meaning
X-Real-IP	Immediate real client IP
X-Forwarded-For	Full proxy chain
"""